### ISSUE TITLE
using custom sonoff firmware without soldering

### ISSUE THREAD

**Issue by eazuka** [mertenats/sonoff#1]
Hi, just came across your sonoff custom firmware just moments ago. Nice work. I have a question though, most custom firmware project i've seen so far for sonoff requires some minor soldering on the sonoff board but looking at your read me doc for this project there isn't any mention of soldering. does it mean with your custom firmware no soldering is required?

**Comment by SamZorSec** [comment]
You just need a FTDI and some wires with male connectors to program the Sonoff. For simplicity I soldered a pin header, but it's not mandatory. You have to press the Sonoff's button before/while you're connecting it to the computer (with the FTDI, NOT to mains power).  
Schematic: https://4.bp.blogspot.com/-o2aOFpB7rC4/Vs29BGlDrWI/AAAAAAAADtw/aqf_o8tulck/s1600/Sonoff_FTDI.jpg
Video about the Sonoff, with explanations: https://www.youtube.com/watch?v=_389pQPLyr8

**Comment by eazuka** [comment]
Ok, thanks
